---
- name: Configure Automation Controller
  hosts: localhost
  vars_files:
    - vars/config-as-code/common.yml
    - vars/config-as-code/controller/credentials.yml
    # - vars/config-as-code/credential_input_sources.yml
    - vars/config-as-code/controller/inventories.yml
    - vars/config-as-code/controller/inventory_sources.yml
    - vars/config-as-code/controller/job_templates.yml
    - vars/config-as-code/controller/organisations.yml
    - vars/config-as-code/controller/projects.yml
    - vars/config-as-code/controller/settings.yml
    - vars/config-as-code/controller/teams.yml
    - vars/config-as-code/controller/users.yml
    - vars/config-as-code/controller/workflow_templates.yml

  roles:
    - infra.controller_configuration.dispatch
