---
- name: Configure Private Automation Hub
  hosts: localhost
  vars_files:
    - vars/config-as-code/common.yml
    - vars/config-as-code/pah/collection_remotes.yml
    - vars/config-as-code/pah/collection_repositories.yml
    - vars/config-as-code/pah/ee_registries.yml

  roles:
    # - infra.ah_configuration.collection_remote
    # - infra.ah_configuration.collection_repository
    - infra.ah_configuration.ee_registry
    - infra.ah_configuration.ee_registry_sync
    # - infra.ah_configuration.collection_repository_sync
