---
controller_credentials:
- name: gitlab
  description: Credentials for GitLab
  organization: ARM organisation
  credential_type: Source Control
  inputs:
    username: person
    password: password

- name: hashivault
  description: HashiCorp Vault Secret Lookup example using token auth
  organization: ARM organisation
  credential_type: HashiCorp Vault Secret Lookup
  inputs:
    url: https://vault.example.com:8243
    token: token
    cacert: "{{ lookup('ansible.builtin.file', '/path/to/ca-certificates.crt') }}"
    api_version: v2

- name: AWS Inventory Credential
  description: AWS credential
  organization: ARM organisation
  credential_type: Amazon Web Services
  inputs:
    access_key: access_key
    secret_key: secret_key

- name: Azure Inventory Credential
  description: Azure inventory credential
  organization: ARM organisation
  credential_type: Microsoft Azure Resource Manager
  inputs:
    subscription_id: sub_id
    username: user 
    password: password
    client_id: client_id
    client_secret: client_secret
    tenant_id: tenant_id

- name: GCP Credential
  description: Google Compute Engine inventory credential
  credential_type: Google Compute Engine
  inputs:
    service_account_email: service_account_email
    private_key: key

- name: Machine Credential
  credential_type: Machine
  inputs:
    username: user
    password: password
    private_key: private key